apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/home/james/.kube/config"
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        enabled:
          - name: CollocationScore
        disabled:
          - name: "*"