apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: collocation-scheduler
    plugins:
      score:
        enabled:
          - name: CollocationScore
            weight: 1
      preScore:
        enabled:
          - name: CollocationScore
