apiVersion: v1
kind: ServiceAccount
metadata:
  name: collocation-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collocation-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: collocation-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collocation-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: collocation-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: collocation-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      nodeSelector:
        nodetype: hfmaster
      serviceAccountName: collocation-scheduler
      containers:
        - command:
            - ./collocation-scheduler
            - --config=scheduler-config.yaml
            - --v=4
          name: collocation-scheduler
          image: kubster96/scheduler:collocation-scheduler-latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []