apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis-my-scheduler
  annotations:
    type: "redis"
    size: "100"
spec:
  schedulerName: collocation-scheduler
  containers:
    - name: redis
      image: redis
  nodeSelector:
    nodetype: worker